spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/javadb
spring.datasource.username=postgres
spring.datasource.password=0
discord.bot.token=${DISCORD_TOKEN}
discord.chat.channel.id=1042878735965245512

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database=POSTGRESQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.application.name=p3
